# Generated by Django 3.2 on 2023-03-27 17:36

from django.db import migrations, models
import reviews.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.IntegerField(null=True, validators=[reviews.validators.validate_one_to_ten]),
        ),
    ]
