# Generated by Django 3.2 on 2023-03-27 17:40

import reviews.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_review_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.IntegerField(default=1, validators=[reviews.validators.validate_one_to_ten]),
            preserve_default=False,
        ),
    ]
