# Generated by Django 3.2 on 2023-04-01 23:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_alter_title_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='review_id',
            new_name='review',
        ),
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.SlugField(unique=True, validators=[django.core.validators.RegexValidator(code='invalid_slug', message='slug must be Alphanumeric', regex='^[-a-zA-Z0-9_]+$')]),
        ),
    ]
